/**
 * Professional franchise + home-venue dataset.
 *
 * These are stable facts (franchise name, home venue, venue coordinates, IANA
 * timezone), which is why they are checked in rather than fetched: they change
 * a few times a decade, and the geofence depends on the coordinates being right.
 * Schedules are the opposite — they change constantly and come from a licensed
 * provider at runtime. See server/src/jobs/proScheduleIngest.ts.
 *
 * Venue coordinates are the stadium/arena centroid. The posting geofence is 3km
 * (server/src/lib/geofencing.ts), which comfortably covers the bowl plus its
 * parking and tailgate footprint, so centroid precision is sufficient.
 *
 * `external_ref` is the stable identity key (`{league}:{slug}`). It must never
 * change once shipped — it is what lets a franchise survive a rename or
 * relocation while keeping its followers. When a team renames, change `name`
 * and leave `external_ref` alone.
 *
 * Trademark posture (see the design spec): names are plain text under nominative
 * fair use, no logos are stored or referenced, and no team gets a handle in the
 * @username namespace. `primary_color` is a single accent color for UI
 * legibility only.
 *
 * VERIFY-BEFORE-LAUNCH: entries flagged `// verify:` below are ones where the
 * venue changed recently or the franchise is newly added, and should be
 * confirmed against the schedule provider's venue feed before going live.
 * The ingester prefers the provider's per-fixture venue whenever it supplies
 * one, so a stale entry here degrades to a fallback rather than a wrong pin.
 */

import type { ProLeague } from '@prisma/client';

export type ProTeamSeed = {
  external_ref: string;
  league: ProLeague;
  name: string;
  short_name: string;
  abbreviation: string;
  city: string | null;
  state: string | null;
  conference: string | null;
  division: string | null;
  venue_name: string | null;
  venue_address: string | null;
  venue_lat: number | null;
  venue_lng: number | null;
  timezone: string | null;
  primary_color: string | null;
  // Free-use (Wikimedia Commons) home-stadium photo for the pro game card
  // backdrop. Optional in the seed: teams without one fall back to the
  // team-color gradient. Sourced as stable commons.wikimedia.org
  // Special:FilePath URLs (see seed values below).
  venue_photo_url?: string | null;
};

const NFL: ProTeamSeed[] = [
  {
    external_ref: 'nfl:arizona-cardinals',
    league: 'nfl',
    name: 'Arizona Cardinals',
    short_name: 'Cardinals',
    abbreviation: 'ARI',
    city: 'Glendale',
    state: 'AZ',
    conference: 'NFC',
    division: 'NFC West',
    venue_name: 'State Farm Stadium',
    venue_address: '1 Cardinals Dr, Glendale, AZ 85305',
    venue_lat: 33.5276,
    venue_lng: -112.2626,
    timezone: 'America/Phoenix',
    primary_color: '#97233F',
  },
  {
    external_ref: 'nfl:atlanta-falcons',
    league: 'nfl',
    name: 'Atlanta Falcons',
    short_name: 'Falcons',
    abbreviation: 'ATL',
    city: 'Atlanta',
    state: 'GA',
    conference: 'NFC',
    division: 'NFC South',
    venue_name: 'Mercedes-Benz Stadium',
    venue_address: '1 AMB Dr NW, Atlanta, GA 30313',
    venue_lat: 33.7554,
    venue_lng: -84.4008,
    timezone: 'America/New_York',
    primary_color: '#A71930',
  },
  {
    external_ref: 'nfl:baltimore-ravens',
    league: 'nfl',
    name: 'Baltimore Ravens',
    short_name: 'Ravens',
    abbreviation: 'BAL',
    city: 'Baltimore',
    state: 'MD',
    conference: 'AFC',
    division: 'AFC North',
    venue_name: 'M&T Bank Stadium',
    venue_address: '1101 Russell St, Baltimore, MD 21230',
    venue_lat: 39.278,
    venue_lng: -76.6227,
    timezone: 'America/New_York',
    primary_color: '#241773',
  },
  {
    external_ref: 'nfl:buffalo-bills',
    league: 'nfl',
    name: 'Buffalo Bills',
    short_name: 'Bills',
    abbreviation: 'BUF',
    city: 'Orchard Park',
    state: 'NY',
    conference: 'AFC',
    division: 'AFC East',
    venue_name: 'Highmark Stadium',
    venue_address: '1 Bills Dr, Orchard Park, NY 14127',
    venue_lat: 42.7738,
    venue_lng: -78.787,
    timezone: 'America/New_York',
    primary_color: '#00338D',
  },
  {
    external_ref: 'nfl:carolina-panthers',
    league: 'nfl',
    name: 'Carolina Panthers',
    short_name: 'Panthers',
    abbreviation: 'CAR',
    city: 'Charlotte',
    state: 'NC',
    conference: 'NFC',
    division: 'NFC South',
    venue_name: 'Bank of America Stadium',
    venue_address: '800 S Mint St, Charlotte, NC 28202',
    venue_lat: 35.2258,
    venue_lng: -80.8528,
    timezone: 'America/New_York',
    primary_color: '#0085CA',
  },
  {
    external_ref: 'nfl:chicago-bears',
    league: 'nfl',
    name: 'Chicago Bears',
    short_name: 'Bears',
    abbreviation: 'CHI',
    city: 'Chicago',
    state: 'IL',
    conference: 'NFC',
    division: 'NFC North',
    venue_name: 'Soldier Field',
    venue_address: '1410 Special Olympics Dr, Chicago, IL 60605',
    venue_lat: 41.8623,
    venue_lng: -87.6167,
    timezone: 'America/Chicago',
    primary_color: '#0B162A',
  },
  {
    external_ref: 'nfl:cincinnati-bengals',
    league: 'nfl',
    name: 'Cincinnati Bengals',
    short_name: 'Bengals',
    abbreviation: 'CIN',
    city: 'Cincinnati',
    state: 'OH',
    conference: 'AFC',
    division: 'AFC North',
    venue_name: 'Paycor Stadium',
    venue_address: '1 Paycor Stadium, Cincinnati, OH 45202',
    venue_lat: 39.0955,
    venue_lng: -84.5161,
    timezone: 'America/New_York',
    primary_color: '#FB4F14',
  },
  {
    // verify: stadium renamed from FirstEnergy/Cleveland Browns Stadium (2024).
    external_ref: 'nfl:cleveland-browns',
    league: 'nfl',
    name: 'Cleveland Browns',
    short_name: 'Browns',
    abbreviation: 'CLE',
    city: 'Cleveland',
    state: 'OH',
    conference: 'AFC',
    division: 'AFC North',
    venue_name: 'Huntington Bank Field',
    venue_address: '100 Alfred Lerner Way, Cleveland, OH 44114',
    venue_lat: 41.5061,
    venue_lng: -81.6995,
    timezone: 'America/New_York',
    primary_color: '#FF3C00',
  },
  {
    external_ref: 'nfl:dallas-cowboys',
    league: 'nfl',
    name: 'Dallas Cowboys',
    short_name: 'Cowboys',
    abbreviation: 'DAL',
    city: 'Arlington',
    state: 'TX',
    conference: 'NFC',
    division: 'NFC East',
    venue_name: 'AT&T Stadium',
    venue_address: '1 AT&T Way, Arlington, TX 76011',
    venue_lat: 32.7473,
    venue_lng: -97.0945,
    timezone: 'America/Chicago',
    primary_color: '#003594',
  },
  {
    external_ref: 'nfl:denver-broncos',
    league: 'nfl',
    name: 'Denver Broncos',
    short_name: 'Broncos',
    abbreviation: 'DEN',
    city: 'Denver',
    state: 'CO',
    conference: 'AFC',
    division: 'AFC West',
    venue_name: 'Empower Field at Mile High',
    venue_address: '1701 Bryant St, Denver, CO 80204',
    venue_lat: 39.7439,
    venue_lng: -105.0201,
    timezone: 'America/Denver',
    primary_color: '#FB4F14',
  },
  {
    external_ref: 'nfl:detroit-lions',
    league: 'nfl',
    name: 'Detroit Lions',
    short_name: 'Lions',
    abbreviation: 'DET',
    city: 'Detroit',
    state: 'MI',
    conference: 'NFC',
    division: 'NFC North',
    venue_name: 'Ford Field',
    venue_address: '2000 Brush St, Detroit, MI 48226',
    venue_lat: 42.34,
    venue_lng: -83.0456,
    timezone: 'America/Detroit',
    primary_color: '#0076B6',
  },
  {
    external_ref: 'nfl:green-bay-packers',
    league: 'nfl',
    name: 'Green Bay Packers',
    short_name: 'Packers',
    abbreviation: 'GB',
    city: 'Green Bay',
    state: 'WI',
    conference: 'NFC',
    division: 'NFC North',
    venue_name: 'Lambeau Field',
    venue_address: '1265 Lombardi Ave, Green Bay, WI 54304',
    venue_lat: 44.5013,
    venue_lng: -88.0622,
    timezone: 'America/Chicago',
    primary_color: '#203731',
  },
  {
    external_ref: 'nfl:houston-texans',
    league: 'nfl',
    name: 'Houston Texans',
    short_name: 'Texans',
    abbreviation: 'HOU',
    city: 'Houston',
    state: 'TX',
    conference: 'AFC',
    division: 'AFC South',
    venue_name: 'NRG Stadium',
    venue_address: '1 NRG Pkwy, Houston, TX 77054',
    venue_lat: 29.6847,
    venue_lng: -95.4107,
    timezone: 'America/Chicago',
    primary_color: '#03202F',
  },
  {
    external_ref: 'nfl:indianapolis-colts',
    league: 'nfl',
    name: 'Indianapolis Colts',
    short_name: 'Colts',
    abbreviation: 'IND',
    city: 'Indianapolis',
    state: 'IN',
    conference: 'AFC',
    division: 'AFC South',
    venue_name: 'Lucas Oil Stadium',
    venue_address: '500 S Capitol Ave, Indianapolis, IN 46225',
    venue_lat: 39.7601,
    venue_lng: -86.1639,
    timezone: 'America/Indiana/Indianapolis',
    primary_color: '#002C5F',
  },
  {
    // verify: stadium renamed from TIAA Bank Field (2023).
    external_ref: 'nfl:jacksonville-jaguars',
    league: 'nfl',
    name: 'Jacksonville Jaguars',
    short_name: 'Jaguars',
    abbreviation: 'JAX',
    city: 'Jacksonville',
    state: 'FL',
    conference: 'AFC',
    division: 'AFC South',
    venue_name: 'EverBank Stadium',
    venue_address: '1 EverBank Stadium Dr, Jacksonville, FL 32202',
    venue_lat: 30.3239,
    venue_lng: -81.6373,
    timezone: 'America/New_York',
    primary_color: '#006778',
  },
  {
    external_ref: 'nfl:kansas-city-chiefs',
    league: 'nfl',
    name: 'Kansas City Chiefs',
    short_name: 'Chiefs',
    abbreviation: 'KC',
    city: 'Kansas City',
    state: 'MO',
    conference: 'AFC',
    division: 'AFC West',
    venue_name: 'GEHA Field at Arrowhead Stadium',
    venue_address: '1 Arrowhead Dr, Kansas City, MO 64129',
    venue_lat: 39.0489,
    venue_lng: -94.4839,
    timezone: 'America/Chicago',
    primary_color: '#E31837',
  },
  {
    external_ref: 'nfl:las-vegas-raiders',
    league: 'nfl',
    name: 'Las Vegas Raiders',
    short_name: 'Raiders',
    abbreviation: 'LV',
    city: 'Las Vegas',
    state: 'NV',
    conference: 'AFC',
    division: 'AFC West',
    venue_name: 'Allegiant Stadium',
    venue_address: '3333 Al Davis Way, Las Vegas, NV 89118',
    venue_lat: 36.0909,
    venue_lng: -115.1833,
    timezone: 'America/Los_Angeles',
    primary_color: '#000000',
  },
  {
    // Shares SoFi Stadium with the Rams — two ProTeam rows, one venue, which is
    // fine: the geofence is per-event and both teams' fixtures pin identically.
    external_ref: 'nfl:los-angeles-chargers',
    league: 'nfl',
    name: 'Los Angeles Chargers',
    short_name: 'Chargers',
    abbreviation: 'LAC',
    city: 'Inglewood',
    state: 'CA',
    conference: 'AFC',
    division: 'AFC West',
    venue_name: 'SoFi Stadium',
    venue_address: '1001 S Stadium Dr, Inglewood, CA 90301',
    venue_lat: 33.9535,
    venue_lng: -118.3392,
    timezone: 'America/Los_Angeles',
    primary_color: '#0080C6',
  },
  {
    external_ref: 'nfl:los-angeles-rams',
    league: 'nfl',
    name: 'Los Angeles Rams',
    short_name: 'Rams',
    abbreviation: 'LAR',
    city: 'Inglewood',
    state: 'CA',
    conference: 'NFC',
    division: 'NFC West',
    venue_name: 'SoFi Stadium',
    venue_address: '1001 S Stadium Dr, Inglewood, CA 90301',
    venue_lat: 33.9535,
    venue_lng: -118.3392,
    timezone: 'America/Los_Angeles',
    primary_color: '#003594',
  },
  {
    external_ref: 'nfl:miami-dolphins',
    league: 'nfl',
    name: 'Miami Dolphins',
    short_name: 'Dolphins',
    abbreviation: 'MIA',
    city: 'Miami Gardens',
    state: 'FL',
    conference: 'AFC',
    division: 'AFC East',
    venue_name: 'Hard Rock Stadium',
    venue_address: '347 Don Shula Dr, Miami Gardens, FL 33056',
    venue_lat: 25.958,
    venue_lng: -80.2389,
    timezone: 'America/New_York',
    primary_color: '#008E97',
  },
  {
    external_ref: 'nfl:minnesota-vikings',
    league: 'nfl',
    name: 'Minnesota Vikings',
    short_name: 'Vikings',
    abbreviation: 'MIN',
    city: 'Minneapolis',
    state: 'MN',
    conference: 'NFC',
    division: 'NFC North',
    venue_name: 'U.S. Bank Stadium',
    venue_address: '401 Chicago Ave, Minneapolis, MN 55415',
    venue_lat: 44.9738,
    venue_lng: -93.2578,
    timezone: 'America/Chicago',
    primary_color: '#4F2683',
  },
  {
    external_ref: 'nfl:new-england-patriots',
    league: 'nfl',
    name: 'New England Patriots',
    short_name: 'Patriots',
    abbreviation: 'NE',
    city: 'Foxborough',
    state: 'MA',
    conference: 'AFC',
    division: 'AFC East',
    venue_name: 'Gillette Stadium',
    venue_address: '1 Patriot Pl, Foxborough, MA 02035',
    venue_lat: 42.0909,
    venue_lng: -71.2643,
    timezone: 'America/New_York',
    primary_color: '#002244',
  },
  {
    external_ref: 'nfl:new-orleans-saints',
    league: 'nfl',
    name: 'New Orleans Saints',
    short_name: 'Saints',
    abbreviation: 'NO',
    city: 'New Orleans',
    state: 'LA',
    conference: 'NFC',
    division: 'NFC South',
    venue_name: 'Caesars Superdome',
    venue_address: '1500 Sugar Bowl Dr, New Orleans, LA 70112',
    venue_lat: 29.9511,
    venue_lng: -90.0812,
    timezone: 'America/Chicago',
    primary_color: '#D3BC8D',
  },
  {
    external_ref: 'nfl:new-york-giants',
    league: 'nfl',
    name: 'New York Giants',
    short_name: 'Giants',
    abbreviation: 'NYG',
    city: 'East Rutherford',
    state: 'NJ',
    conference: 'NFC',
    division: 'NFC East',
    venue_name: 'MetLife Stadium',
    venue_address: '1 MetLife Stadium Dr, East Rutherford, NJ 07073',
    venue_lat: 40.8135,
    venue_lng: -74.0745,
    timezone: 'America/New_York',
    primary_color: '#0B2265',
  },
  {
    external_ref: 'nfl:new-york-jets',
    league: 'nfl',
    name: 'New York Jets',
    short_name: 'Jets',
    abbreviation: 'NYJ',
    city: 'East Rutherford',
    state: 'NJ',
    conference: 'AFC',
    division: 'AFC East',
    venue_name: 'MetLife Stadium',
    venue_address: '1 MetLife Stadium Dr, East Rutherford, NJ 07073',
    venue_lat: 40.8135,
    venue_lng: -74.0745,
    timezone: 'America/New_York',
    primary_color: '#125740',
  },
  {
    external_ref: 'nfl:philadelphia-eagles',
    league: 'nfl',
    name: 'Philadelphia Eagles',
    short_name: 'Eagles',
    abbreviation: 'PHI',
    city: 'Philadelphia',
    state: 'PA',
    conference: 'NFC',
    division: 'NFC East',
    venue_name: 'Lincoln Financial Field',
    venue_address: '1 Lincoln Financial Field Way, Philadelphia, PA 19148',
    venue_lat: 39.9008,
    venue_lng: -75.1675,
    timezone: 'America/New_York',
    primary_color: '#004C54',
  },
  {
    external_ref: 'nfl:pittsburgh-steelers',
    league: 'nfl',
    name: 'Pittsburgh Steelers',
    short_name: 'Steelers',
    abbreviation: 'PIT',
    city: 'Pittsburgh',
    state: 'PA',
    conference: 'AFC',
    division: 'AFC North',
    venue_name: 'Acrisure Stadium',
    venue_address: '100 Art Rooney Ave, Pittsburgh, PA 15212',
    venue_lat: 40.4468,
    venue_lng: -80.0158,
    timezone: 'America/New_York',
    primary_color: '#FFB612',
  },
  {
    external_ref: 'nfl:san-francisco-49ers',
    league: 'nfl',
    name: 'San Francisco 49ers',
    short_name: '49ers',
    abbreviation: 'SF',
    city: 'Santa Clara',
    state: 'CA',
    conference: 'NFC',
    division: 'NFC West',
    venue_name: "Levi's Stadium",
    venue_address: '4900 Marie P DeBartolo Way, Santa Clara, CA 95054',
    venue_lat: 37.4033,
    venue_lng: -121.9694,
    timezone: 'America/Los_Angeles',
    primary_color: '#AA0000',
  },
  {
    external_ref: 'nfl:seattle-seahawks',
    league: 'nfl',
    name: 'Seattle Seahawks',
    short_name: 'Seahawks',
    abbreviation: 'SEA',
    city: 'Seattle',
    state: 'WA',
    conference: 'NFC',
    division: 'NFC West',
    venue_name: 'Lumen Field',
    venue_address: '800 Occidental Ave S, Seattle, WA 98134',
    venue_lat: 47.5952,
    venue_lng: -122.3316,
    timezone: 'America/Los_Angeles',
    primary_color: '#002244',
  },
  {
    external_ref: 'nfl:tampa-bay-buccaneers',
    league: 'nfl',
    name: 'Tampa Bay Buccaneers',
    short_name: 'Buccaneers',
    abbreviation: 'TB',
    city: 'Tampa',
    state: 'FL',
    conference: 'NFC',
    division: 'NFC South',
    venue_name: 'Raymond James Stadium',
    venue_address: '4201 N Dale Mabry Hwy, Tampa, FL 33607',
    venue_lat: 27.9759,
    venue_lng: -82.5033,
    timezone: 'America/New_York',
    primary_color: '#D50A0A',
  },
  {
    external_ref: 'nfl:tennessee-titans',
    league: 'nfl',
    name: 'Tennessee Titans',
    short_name: 'Titans',
    abbreviation: 'TEN',
    city: 'Nashville',
    state: 'TN',
    conference: 'AFC',
    division: 'AFC South',
    venue_name: 'Nissan Stadium',
    venue_address: '1 Titans Way, Nashville, TN 37213',
    venue_lat: 36.1665,
    venue_lng: -86.7713,
    timezone: 'America/Chicago',
    primary_color: '#0C2340',
  },
  {
    // verify: stadium renamed from FedExField (2024).
    external_ref: 'nfl:washington-commanders',
    league: 'nfl',
    name: 'Washington Commanders',
    short_name: 'Commanders',
    abbreviation: 'WAS',
    city: 'Landover',
    state: 'MD',
    conference: 'NFC',
    division: 'NFC East',
    venue_name: 'Northwest Stadium',
    venue_address: '1600 Fedex Way, Landover, MD 20785',
    venue_lat: 38.9077,
    venue_lng: -76.8645,
    timezone: 'America/New_York',
    primary_color: '#5A1414',
  },
];

const NBA: ProTeamSeed[] = [
  {
    external_ref: 'nba:atlanta-hawks',
    league: 'nba',
    name: 'Atlanta Hawks',
    short_name: 'Hawks',
    abbreviation: 'ATL',
    city: 'Atlanta',
    state: 'GA',
    conference: 'Eastern',
    division: 'Southeast',
    venue_name: 'State Farm Arena',
    venue_address: '1 State Farm Dr, Atlanta, GA 30303',
    venue_lat: 33.7573,
    venue_lng: -84.3963,
    timezone: 'America/New_York',
    primary_color: '#E03A3E',
  },
  {
    external_ref: 'nba:boston-celtics',
    league: 'nba',
    name: 'Boston Celtics',
    short_name: 'Celtics',
    abbreviation: 'BOS',
    city: 'Boston',
    state: 'MA',
    conference: 'Eastern',
    division: 'Atlantic',
    venue_name: 'TD Garden',
    venue_address: '100 Legends Way, Boston, MA 02114',
    venue_lat: 42.3662,
    venue_lng: -71.0621,
    timezone: 'America/New_York',
    primary_color: '#007A33',
  },
  {
    external_ref: 'nba:brooklyn-nets',
    league: 'nba',
    name: 'Brooklyn Nets',
    short_name: 'Nets',
    abbreviation: 'BKN',
    city: 'Brooklyn',
    state: 'NY',
    conference: 'Eastern',
    division: 'Atlantic',
    venue_name: 'Barclays Center',
    venue_address: '620 Atlantic Ave, Brooklyn, NY 11217',
    venue_lat: 40.6826,
    venue_lng: -73.9754,
    timezone: 'America/New_York',
    primary_color: '#000000',
  },
  {
    external_ref: 'nba:charlotte-hornets',
    league: 'nba',
    name: 'Charlotte Hornets',
    short_name: 'Hornets',
    abbreviation: 'CHA',
    city: 'Charlotte',
    state: 'NC',
    conference: 'Eastern',
    division: 'Southeast',
    venue_name: 'Spectrum Center',
    venue_address: '333 E Trade St, Charlotte, NC 28202',
    venue_lat: 35.2251,
    venue_lng: -80.8392,
    timezone: 'America/New_York',
    primary_color: '#1D1160',
  },
  {
    external_ref: 'nba:chicago-bulls',
    league: 'nba',
    name: 'Chicago Bulls',
    short_name: 'Bulls',
    abbreviation: 'CHI',
    city: 'Chicago',
    state: 'IL',
    conference: 'Eastern',
    division: 'Central',
    venue_name: 'United Center',
    venue_address: '1901 W Madison St, Chicago, IL 60612',
    venue_lat: 41.8807,
    venue_lng: -87.6742,
    timezone: 'America/Chicago',
    primary_color: '#CE1141',
  },
  {
    // verify: arena renamed from Rocket Mortgage FieldHouse (2025).
    external_ref: 'nba:cleveland-cavaliers',
    league: 'nba',
    name: 'Cleveland Cavaliers',
    short_name: 'Cavaliers',
    abbreviation: 'CLE',
    city: 'Cleveland',
    state: 'OH',
    conference: 'Eastern',
    division: 'Central',
    venue_name: 'Rocket Arena',
    venue_address: '1 Center Ct, Cleveland, OH 44115',
    venue_lat: 41.4965,
    venue_lng: -81.6882,
    timezone: 'America/New_York',
    primary_color: '#860038',
  },
  {
    external_ref: 'nba:dallas-mavericks',
    league: 'nba',
    name: 'Dallas Mavericks',
    short_name: 'Mavericks',
    abbreviation: 'DAL',
    city: 'Dallas',
    state: 'TX',
    conference: 'Western',
    division: 'Southwest',
    venue_name: 'American Airlines Center',
    venue_address: '2500 Victory Ave, Dallas, TX 75219',
    venue_lat: 32.7905,
    venue_lng: -96.8104,
    timezone: 'America/Chicago',
    primary_color: '#00538C',
  },
  {
    external_ref: 'nba:denver-nuggets',
    league: 'nba',
    name: 'Denver Nuggets',
    short_name: 'Nuggets',
    abbreviation: 'DEN',
    city: 'Denver',
    state: 'CO',
    conference: 'Western',
    division: 'Northwest',
    venue_name: 'Ball Arena',
    venue_address: '1000 Chopper Cir, Denver, CO 80204',
    venue_lat: 39.7487,
    venue_lng: -105.0077,
    timezone: 'America/Denver',
    primary_color: '#0E2240',
  },
  {
    external_ref: 'nba:detroit-pistons',
    league: 'nba',
    name: 'Detroit Pistons',
    short_name: 'Pistons',
    abbreviation: 'DET',
    city: 'Detroit',
    state: 'MI',
    conference: 'Eastern',
    division: 'Central',
    venue_name: 'Little Caesars Arena',
    venue_address: '2645 Woodward Ave, Detroit, MI 48201',
    venue_lat: 42.3411,
    venue_lng: -83.0553,
    timezone: 'America/Detroit',
    primary_color: '#C8102E',
  },
  {
    external_ref: 'nba:golden-state-warriors',
    league: 'nba',
    name: 'Golden State Warriors',
    short_name: 'Warriors',
    abbreviation: 'GSW',
    city: 'San Francisco',
    state: 'CA',
    conference: 'Western',
    division: 'Pacific',
    venue_name: 'Chase Center',
    venue_address: '1 Warriors Way, San Francisco, CA 94158',
    venue_lat: 37.768,
    venue_lng: -122.3878,
    timezone: 'America/Los_Angeles',
    primary_color: '#1D428A',
  },
  {
    external_ref: 'nba:houston-rockets',
    league: 'nba',
    name: 'Houston Rockets',
    short_name: 'Rockets',
    abbreviation: 'HOU',
    city: 'Houston',
    state: 'TX',
    conference: 'Western',
    division: 'Southwest',
    venue_name: 'Toyota Center',
    venue_address: '1510 Polk St, Houston, TX 77002',
    venue_lat: 29.7508,
    venue_lng: -95.3621,
    timezone: 'America/Chicago',
    primary_color: '#CE1141',
  },
  {
    external_ref: 'nba:indiana-pacers',
    league: 'nba',
    name: 'Indiana Pacers',
    short_name: 'Pacers',
    abbreviation: 'IND',
    city: 'Indianapolis',
    state: 'IN',
    conference: 'Eastern',
    division: 'Central',
    venue_name: 'Gainbridge Fieldhouse',
    venue_address: '125 S Pennsylvania St, Indianapolis, IN 46204',
    venue_lat: 39.764,
    venue_lng: -86.1555,
    timezone: 'America/Indiana/Indianapolis',
    primary_color: '#002D62',
  },
  {
    // verify: moved from Crypto.com Arena to Intuit Dome (2024).
    external_ref: 'nba:la-clippers',
    league: 'nba',
    name: 'LA Clippers',
    short_name: 'Clippers',
    abbreviation: 'LAC',
    city: 'Inglewood',
    state: 'CA',
    conference: 'Western',
    division: 'Pacific',
    venue_name: 'Intuit Dome',
    venue_address: '3930 W Century Blvd, Inglewood, CA 90303',
    venue_lat: 33.945,
    venue_lng: -118.3417,
    timezone: 'America/Los_Angeles',
    primary_color: '#C8102E',
  },
  {
    external_ref: 'nba:los-angeles-lakers',
    league: 'nba',
    name: 'Los Angeles Lakers',
    short_name: 'Lakers',
    abbreviation: 'LAL',
    city: 'Los Angeles',
    state: 'CA',
    conference: 'Western',
    division: 'Pacific',
    venue_name: 'Crypto.com Arena',
    venue_address: '1111 S Figueroa St, Los Angeles, CA 90015',
    venue_lat: 34.043,
    venue_lng: -118.2673,
    timezone: 'America/Los_Angeles',
    primary_color: '#552583',
  },
  {
    external_ref: 'nba:memphis-grizzlies',
    league: 'nba',
    name: 'Memphis Grizzlies',
    short_name: 'Grizzlies',
    abbreviation: 'MEM',
    city: 'Memphis',
    state: 'TN',
    conference: 'Western',
    division: 'Southwest',
    venue_name: 'FedExForum',
    venue_address: '191 Beale St, Memphis, TN 38103',
    venue_lat: 35.1382,
    venue_lng: -90.0505,
    timezone: 'America/Chicago',
    primary_color: '#5D76A9',
  },
  {
    // verify: arena renamed from FTX Arena / American Airlines Arena (2023).
    external_ref: 'nba:miami-heat',
    league: 'nba',
    name: 'Miami Heat',
    short_name: 'Heat',
    abbreviation: 'MIA',
    city: 'Miami',
    state: 'FL',
    conference: 'Eastern',
    division: 'Southeast',
    venue_name: 'Kaseya Center',
    venue_address: '601 Biscayne Blvd, Miami, FL 33132',
    venue_lat: 25.7814,
    venue_lng: -80.187,
    timezone: 'America/New_York',
    primary_color: '#98002E',
  },
  {
    external_ref: 'nba:milwaukee-bucks',
    league: 'nba',
    name: 'Milwaukee Bucks',
    short_name: 'Bucks',
    abbreviation: 'MIL',
    city: 'Milwaukee',
    state: 'WI',
    conference: 'Eastern',
    division: 'Central',
    venue_name: 'Fiserv Forum',
    venue_address: '1111 Vel R. Phillips Ave, Milwaukee, WI 53203',
    venue_lat: 43.0451,
    venue_lng: -87.9172,
    timezone: 'America/Chicago',
    primary_color: '#00471B',
  },
  {
    external_ref: 'nba:minnesota-timberwolves',
    league: 'nba',
    name: 'Minnesota Timberwolves',
    short_name: 'Timberwolves',
    abbreviation: 'MIN',
    city: 'Minneapolis',
    state: 'MN',
    conference: 'Western',
    division: 'Northwest',
    venue_name: 'Target Center',
    venue_address: '600 N 1st Ave, Minneapolis, MN 55403',
    venue_lat: 44.9795,
    venue_lng: -93.2761,
    timezone: 'America/Chicago',
    primary_color: '#0C2340',
  },
  {
    external_ref: 'nba:new-orleans-pelicans',
    league: 'nba',
    name: 'New Orleans Pelicans',
    short_name: 'Pelicans',
    abbreviation: 'NOP',
    city: 'New Orleans',
    state: 'LA',
    conference: 'Western',
    division: 'Southwest',
    venue_name: 'Smoothie King Center',
    venue_address: '1501 Dave Dixon Dr, New Orleans, LA 70113',
    venue_lat: 29.949,
    venue_lng: -90.0821,
    timezone: 'America/Chicago',
    primary_color: '#0C2340',
  },
  {
    external_ref: 'nba:new-york-knicks',
    league: 'nba',
    name: 'New York Knicks',
    short_name: 'Knicks',
    abbreviation: 'NYK',
    city: 'New York',
    state: 'NY',
    conference: 'Eastern',
    division: 'Atlantic',
    venue_name: 'Madison Square Garden',
    venue_address: '4 Pennsylvania Plaza, New York, NY 10001',
    venue_lat: 40.7505,
    venue_lng: -73.9934,
    timezone: 'America/New_York',
    primary_color: '#006BB6',
  },
  {
    external_ref: 'nba:oklahoma-city-thunder',
    league: 'nba',
    name: 'Oklahoma City Thunder',
    short_name: 'Thunder',
    abbreviation: 'OKC',
    city: 'Oklahoma City',
    state: 'OK',
    conference: 'Western',
    division: 'Northwest',
    venue_name: 'Paycom Center',
    venue_address: '100 W Reno Ave, Oklahoma City, OK 73102',
    venue_lat: 35.4634,
    venue_lng: -97.5151,
    timezone: 'America/Chicago',
    primary_color: '#007AC1',
  },
  {
    // verify: arena renamed from Amway Center (2023).
    external_ref: 'nba:orlando-magic',
    league: 'nba',
    name: 'Orlando Magic',
    short_name: 'Magic',
    abbreviation: 'ORL',
    city: 'Orlando',
    state: 'FL',
    conference: 'Eastern',
    division: 'Southeast',
    venue_name: 'Kia Center',
    venue_address: '400 W Church St, Orlando, FL 32801',
    venue_lat: 28.5392,
    venue_lng: -81.3839,
    timezone: 'America/New_York',
    primary_color: '#0077C0',
  },
  {
    // verify: arena renamed from Wells Fargo Center (2025).
    external_ref: 'nba:philadelphia-76ers',
    league: 'nba',
    name: 'Philadelphia 76ers',
    short_name: '76ers',
    abbreviation: 'PHI',
    city: 'Philadelphia',
    state: 'PA',
    conference: 'Eastern',
    division: 'Atlantic',
    venue_name: 'Xfinity Mobile Arena',
    venue_address: '3601 S Broad St, Philadelphia, PA 19148',
    venue_lat: 39.9012,
    venue_lng: -75.172,
    timezone: 'America/New_York',
    primary_color: '#006BB6',
  },
  {
    // verify: arena renamed from Footprint Center (2025).
    external_ref: 'nba:phoenix-suns',
    league: 'nba',
    name: 'Phoenix Suns',
    short_name: 'Suns',
    abbreviation: 'PHX',
    city: 'Phoenix',
    state: 'AZ',
    conference: 'Western',
    division: 'Pacific',
    venue_name: 'Mortgage Matchup Center',
    venue_address: '201 E Jefferson St, Phoenix, AZ 85004',
    venue_lat: 33.4457,
    venue_lng: -112.0712,
    timezone: 'America/Phoenix',
    primary_color: '#1D1160',
  },
  {
    external_ref: 'nba:portland-trail-blazers',
    league: 'nba',
    name: 'Portland Trail Blazers',
    short_name: 'Trail Blazers',
    abbreviation: 'POR',
    city: 'Portland',
    state: 'OR',
    conference: 'Western',
    division: 'Northwest',
    venue_name: 'Moda Center',
    venue_address: '1 N Center Court St, Portland, OR 97227',
    venue_lat: 45.5316,
    venue_lng: -122.6668,
    timezone: 'America/Los_Angeles',
    primary_color: '#E03A3E',
  },
  {
    external_ref: 'nba:sacramento-kings',
    league: 'nba',
    name: 'Sacramento Kings',
    short_name: 'Kings',
    abbreviation: 'SAC',
    city: 'Sacramento',
    state: 'CA',
    conference: 'Western',
    division: 'Pacific',
    venue_name: 'Golden 1 Center',
    venue_address: '500 David J Stern Walk, Sacramento, CA 95814',
    venue_lat: 38.5802,
    venue_lng: -121.4997,
    timezone: 'America/Los_Angeles',
    primary_color: '#5A2D81',
  },
  {
    // verify: arena renamed from AT&T Center (2023).
    external_ref: 'nba:san-antonio-spurs',
    league: 'nba',
    name: 'San Antonio Spurs',
    short_name: 'Spurs',
    abbreviation: 'SAS',
    city: 'San Antonio',
    state: 'TX',
    conference: 'Western',
    division: 'Southwest',
    venue_name: 'Frost Bank Center',
    venue_address: '1 AT&T Center Pkwy, San Antonio, TX 78219',
    venue_lat: 29.427,
    venue_lng: -98.4375,
    timezone: 'America/Chicago',
    primary_color: '#C4CED4',
  },
  {
    external_ref: 'nba:toronto-raptors',
    league: 'nba',
    name: 'Toronto Raptors',
    short_name: 'Raptors',
    abbreviation: 'TOR',
    city: 'Toronto',
    state: 'ON',
    conference: 'Eastern',
    division: 'Atlantic',
    venue_name: 'Scotiabank Arena',
    venue_address: '40 Bay St, Toronto, ON M5J 2X2',
    venue_lat: 43.6435,
    venue_lng: -79.3791,
    timezone: 'America/Toronto',
    primary_color: '#CE1141',
  },
  {
    // verify: arena renamed from Vivint Arena back to Delta Center (2023).
    external_ref: 'nba:utah-jazz',
    league: 'nba',
    name: 'Utah Jazz',
    short_name: 'Jazz',
    abbreviation: 'UTA',
    city: 'Salt Lake City',
    state: 'UT',
    conference: 'Western',
    division: 'Northwest',
    venue_name: 'Delta Center',
    venue_address: '301 S Temple, Salt Lake City, UT 84101',
    venue_lat: 40.7683,
    venue_lng: -111.9011,
    timezone: 'America/Denver',
    primary_color: '#002B5C',
  },
  {
    external_ref: 'nba:washington-wizards',
    league: 'nba',
    name: 'Washington Wizards',
    short_name: 'Wizards',
    abbreviation: 'WAS',
    city: 'Washington',
    state: 'DC',
    conference: 'Eastern',
    division: 'Southeast',
    venue_name: 'Capital One Arena',
    venue_address: '601 F St NW, Washington, DC 20004',
    venue_lat: 38.8981,
    venue_lng: -77.0209,
    timezone: 'America/New_York',
    primary_color: '#002B5C',
  },
];

const MLB: ProTeamSeed[] = [
  {
    external_ref: 'mlb:arizona-diamondbacks',
    league: 'mlb',
    name: 'Arizona Diamondbacks',
    short_name: 'Diamondbacks',
    abbreviation: 'ARI',
    city: 'Phoenix',
    state: 'AZ',
    conference: 'National League',
    division: 'NL West',
    venue_name: 'Chase Field',
    venue_address: '401 E Jefferson St, Phoenix, AZ 85004',
    venue_lat: 33.4455,
    venue_lng: -112.0667,
    timezone: 'America/Phoenix',
    primary_color: '#A71930',
    venue_photo_url:
      'https://commons.wikimedia.org/wiki/Special:FilePath/Chase%20Field%2C%20July%203%2C%202021.jpg?width=1200',
  },
  {
    external_ref: 'mlb:atlanta-braves',
    league: 'mlb',
    name: 'Atlanta Braves',
    short_name: 'Braves',
    abbreviation: 'ATL',
    city: 'Cumberland',
    state: 'GA',
    conference: 'National League',
    division: 'NL East',
    venue_name: 'Truist Park',
    venue_address: '755 Battery Ave SE, Atlanta, GA 30339',
    venue_lat: 33.8907,
    venue_lng: -84.4677,
    timezone: 'America/New_York',
    primary_color: '#CE1141',
    venue_photo_url:
      'https://commons.wikimedia.org/wiki/Special:FilePath/SunTrust%20Park%20Opening%20Day%202017.jpg?width=1200',
  },
  {
    external_ref: 'mlb:baltimore-orioles',
    league: 'mlb',
    name: 'Baltimore Orioles',
    short_name: 'Orioles',
    abbreviation: 'BAL',
    city: 'Baltimore',
    state: 'MD',
    conference: 'American League',
    division: 'AL East',
    venue_name: 'Oriole Park at Camden Yards',
    venue_address: '333 W Camden St, Baltimore, MD 21201',
    venue_lat: 39.2839,
    venue_lng: -76.6217,
    timezone: 'America/New_York',
    primary_color: '#DF4601',
    venue_photo_url:
      'https://commons.wikimedia.org/wiki/Special:FilePath/OrioleParkAtCamdenYardsJune2013.jpg?width=1200',
  },
  {
    external_ref: 'mlb:boston-red-sox',
    league: 'mlb',
    name: 'Boston Red Sox',
    short_name: 'Red Sox',
    abbreviation: 'BOS',
    city: 'Boston',
    state: 'MA',
    conference: 'American League',
    division: 'AL East',
    venue_name: 'Fenway Park',
    venue_address: '4 Jersey St, Boston, MA 02215',
    venue_lat: 42.3467,
    venue_lng: -71.0972,
    timezone: 'America/New_York',
    primary_color: '#BD3039',
    venue_photo_url:
      'https://commons.wikimedia.org/wiki/Special:FilePath/Fenway%20Park.jpg?width=1200',
  },
  {
    external_ref: 'mlb:chicago-cubs',
    league: 'mlb',
    name: 'Chicago Cubs',
    short_name: 'Cubs',
    abbreviation: 'CHC',
    city: 'Chicago',
    state: 'IL',
    conference: 'National League',
    division: 'NL Central',
    venue_name: 'Wrigley Field',
    venue_address: '1060 W Addison St, Chicago, IL 60613',
    venue_lat: 41.9484,
    venue_lng: -87.6553,
    timezone: 'America/Chicago',
    primary_color: '#0E3386',
    venue_photo_url:
      'https://commons.wikimedia.org/wiki/Special:FilePath/Wrigley%20Field%2C%20Chicago%2C%20Illinois%20(42488207635).jpg?width=1200',
  },
  {
    // verify: ballpark renamed from Guaranteed Rate Field (2025).
    external_ref: 'mlb:chicago-white-sox',
    league: 'mlb',
    name: 'Chicago White Sox',
    short_name: 'White Sox',
    abbreviation: 'CWS',
    city: 'Chicago',
    state: 'IL',
    conference: 'American League',
    division: 'AL Central',
    venue_name: 'Rate Field',
    venue_address: '333 W 35th St, Chicago, IL 60616',
    venue_lat: 41.8299,
    venue_lng: -87.6338,
    timezone: 'America/Chicago',
    primary_color: '#27251F',
    venue_photo_url:
      'https://commons.wikimedia.org/wiki/Special:FilePath/U.S.%20Cellular%20Field%20(30972191694).jpg?width=1200',
  },
  {
    external_ref: 'mlb:cincinnati-reds',
    league: 'mlb',
    name: 'Cincinnati Reds',
    short_name: 'Reds',
    abbreviation: 'CIN',
    city: 'Cincinnati',
    state: 'OH',
    conference: 'National League',
    division: 'NL Central',
    venue_name: 'Great American Ball Park',
    venue_address: '100 Joe Nuxhall Way, Cincinnati, OH 45202',
    venue_lat: 39.0975,
    venue_lng: -84.5069,
    timezone: 'America/New_York',
    primary_color: '#C6011F',
    venue_photo_url:
      'https://commons.wikimedia.org/wiki/Special:FilePath/Great%20American%20Ballpark%202007.jpg?width=1200',
  },
  {
    external_ref: 'mlb:cleveland-guardians',
    league: 'mlb',
    name: 'Cleveland Guardians',
    short_name: 'Guardians',
    abbreviation: 'CLE',
    city: 'Cleveland',
    state: 'OH',
    conference: 'American League',
    division: 'AL Central',
    venue_name: 'Progressive Field',
    venue_address: '2401 Ontario St, Cleveland, OH 44115',
    venue_lat: 41.4962,
    venue_lng: -81.6852,
    timezone: 'America/New_York',
    primary_color: '#00385D',
    venue_photo_url:
      'https://commons.wikimedia.org/wiki/Special:FilePath/Progressive%20Field%20aerial%202015.jpg?width=1200',
  },
  {
    external_ref: 'mlb:colorado-rockies',
    league: 'mlb',
    name: 'Colorado Rockies',
    short_name: 'Rockies',
    abbreviation: 'COL',
    city: 'Denver',
    state: 'CO',
    conference: 'National League',
    division: 'NL West',
    venue_name: 'Coors Field',
    venue_address: '2001 Blake St, Denver, CO 80205',
    venue_lat: 39.7559,
    venue_lng: -104.9942,
    timezone: 'America/Denver',
    primary_color: '#33006F',
    venue_photo_url:
      'https://commons.wikimedia.org/wiki/Special:FilePath/Coors%20field%20aerial%201.JPG?width=1200',
  },
  {
    external_ref: 'mlb:detroit-tigers',
    league: 'mlb',
    name: 'Detroit Tigers',
    short_name: 'Tigers',
    abbreviation: 'DET',
    city: 'Detroit',
    state: 'MI',
    conference: 'American League',
    division: 'AL Central',
    venue_name: 'Comerica Park',
    venue_address: '2100 Woodward Ave, Detroit, MI 48201',
    venue_lat: 42.339,
    venue_lng: -83.0485,
    timezone: 'America/Detroit',
    primary_color: '#0C2340',
    venue_photo_url:
      'https://commons.wikimedia.org/wiki/Special:FilePath/Comerica%20Park%2C%20Home%20of%20the%20Detroit%20Tigers%20Baseball%20Team.jpg?width=1200',
  },
  {
    // verify: ballpark renamed from Minute Maid Park (2025).
    external_ref: 'mlb:houston-astros',
    league: 'mlb',
    name: 'Houston Astros',
    short_name: 'Astros',
    abbreviation: 'HOU',
    city: 'Houston',
    state: 'TX',
    conference: 'American League',
    division: 'AL West',
    venue_name: 'Daikin Park',
    venue_address: '501 Crawford St, Houston, TX 77002',
    venue_lat: 29.7573,
    venue_lng: -95.3555,
    timezone: 'America/Chicago',
    primary_color: '#EB6E1F',
    venue_photo_url:
      'https://commons.wikimedia.org/wiki/Special:FilePath/Minute%20Maid%20Park%202010.JPG?width=1200',
  },
  {
    external_ref: 'mlb:kansas-city-royals',
    league: 'mlb',
    name: 'Kansas City Royals',
    short_name: 'Royals',
    abbreviation: 'KC',
    city: 'Kansas City',
    state: 'MO',
    conference: 'American League',
    division: 'AL Central',
    venue_name: 'Kauffman Stadium',
    venue_address: '1 Royal Way, Kansas City, MO 64129',
    venue_lat: 39.0517,
    venue_lng: -94.4803,
    timezone: 'America/Chicago',
    primary_color: '#004687',
    venue_photo_url:
      'https://commons.wikimedia.org/wiki/Special:FilePath/NewKauffman.jpg?width=1200',
  },
  {
    external_ref: 'mlb:los-angeles-angels',
    league: 'mlb',
    name: 'Los Angeles Angels',
    short_name: 'Angels',
    abbreviation: 'LAA',
    city: 'Anaheim',
    state: 'CA',
    conference: 'American League',
    division: 'AL West',
    venue_name: 'Angel Stadium',
    venue_address: '2000 E Gene Autry Way, Anaheim, CA 92806',
    venue_lat: 33.8003,
    venue_lng: -117.8827,
    timezone: 'America/Los_Angeles',
    primary_color: '#BA0021',
    venue_photo_url:
      'https://commons.wikimedia.org/wiki/Special:FilePath/Angel%20Stadium%20of%20Anaheim.jpg?width=1200',
  },
  {
    external_ref: 'mlb:los-angeles-dodgers',
    league: 'mlb',
    name: 'Los Angeles Dodgers',
    short_name: 'Dodgers',
    abbreviation: 'LAD',
    city: 'Los Angeles',
    state: 'CA',
    conference: 'National League',
    division: 'NL West',
    venue_name: 'Dodger Stadium',
    venue_address: '1000 Vin Scully Ave, Los Angeles, CA 90012',
    venue_lat: 34.0739,
    venue_lng: -118.24,
    timezone: 'America/Los_Angeles',
    primary_color: '#005A9C',
    venue_photo_url:
      'https://commons.wikimedia.org/wiki/Special:FilePath/Aerial%20view%20of%20Dodger%20Stadium%2C%20April%202024.JPG?width=1200',
  },
  {
    external_ref: 'mlb:miami-marlins',
    league: 'mlb',
    name: 'Miami Marlins',
    short_name: 'Marlins',
    abbreviation: 'MIA',
    city: 'Miami',
    state: 'FL',
    conference: 'National League',
    division: 'NL East',
    venue_name: 'loanDepot park',
    venue_address: '501 Marlins Way, Miami, FL 33125',
    venue_lat: 25.7781,
    venue_lng: -80.2197,
    timezone: 'America/New_York',
    primary_color: '#00A3E0',
  },
  {
    external_ref: 'mlb:milwaukee-brewers',
    league: 'mlb',
    name: 'Milwaukee Brewers',
    short_name: 'Brewers',
    abbreviation: 'MIL',
    city: 'Milwaukee',
    state: 'WI',
    conference: 'National League',
    division: 'NL Central',
    venue_name: 'American Family Field',
    venue_address: '1 Brewers Way, Milwaukee, WI 53214',
    venue_lat: 43.028,
    venue_lng: -87.9712,
    timezone: 'America/Chicago',
    primary_color: '#12284B',
  },
  {
    external_ref: 'mlb:minnesota-twins',
    league: 'mlb',
    name: 'Minnesota Twins',
    short_name: 'Twins',
    abbreviation: 'MIN',
    city: 'Minneapolis',
    state: 'MN',
    conference: 'American League',
    division: 'AL Central',
    venue_name: 'Target Field',
    venue_address: '1 Twins Way, Minneapolis, MN 55403',
    venue_lat: 44.9817,
    venue_lng: -93.2775,
    timezone: 'America/Chicago',
    primary_color: '#002B5C',
    venue_photo_url:
      'https://commons.wikimedia.org/wiki/Special:FilePath/Target%20Field%20Aerial.jpg?width=1200',
  },
  {
    external_ref: 'mlb:new-york-mets',
    league: 'mlb',
    name: 'New York Mets',
    short_name: 'Mets',
    abbreviation: 'NYM',
    city: 'Queens',
    state: 'NY',
    conference: 'National League',
    division: 'NL East',
    venue_name: 'Citi Field',
    venue_address: '41 Seaver Way, Queens, NY 11368',
    venue_lat: 40.7571,
    venue_lng: -73.8458,
    timezone: 'America/New_York',
    primary_color: '#002D72',
    venue_photo_url:
      'https://commons.wikimedia.org/wiki/Special:FilePath/Aerial%20Shot%20of%20Citi%20Field%20Opening%20Day%20April%2013th%202009.jpg?width=1200',
  },
  {
    external_ref: 'mlb:new-york-yankees',
    league: 'mlb',
    name: 'New York Yankees',
    short_name: 'Yankees',
    abbreviation: 'NYY',
    city: 'Bronx',
    state: 'NY',
    conference: 'American League',
    division: 'AL East',
    venue_name: 'Yankee Stadium',
    venue_address: '1 E 161st St, Bronx, NY 10451',
    venue_lat: 40.8296,
    venue_lng: -73.9262,
    timezone: 'America/New_York',
    primary_color: '#003087',
    venue_photo_url:
      'https://commons.wikimedia.org/wiki/Special:FilePath/Yankee%20Stadium%202009.jpg?width=1200',
  },
  {
    // verify: relocated from Oakland (2025) and now branded without a city.
    // Sutter Health Park is a temporary home pending the Las Vegas move.
    external_ref: 'mlb:athletics',
    league: 'mlb',
    name: 'Athletics',
    short_name: 'Athletics',
    abbreviation: 'ATH',
    city: 'West Sacramento',
    state: 'CA',
    conference: 'American League',
    division: 'AL West',
    venue_name: 'Sutter Health Park',
    venue_address: '400 Ballpark Dr, West Sacramento, CA 95691',
    venue_lat: 38.5802,
    venue_lng: -121.5133,
    timezone: 'America/Los_Angeles',
    primary_color: '#003831',
  },
  {
    external_ref: 'mlb:philadelphia-phillies',
    league: 'mlb',
    name: 'Philadelphia Phillies',
    short_name: 'Phillies',
    abbreviation: 'PHI',
    city: 'Philadelphia',
    state: 'PA',
    conference: 'National League',
    division: 'NL East',
    venue_name: 'Citizens Bank Park',
    venue_address: '1 Citizens Bank Way, Philadelphia, PA 19148',
    venue_lat: 39.9061,
    venue_lng: -75.1665,
    timezone: 'America/New_York',
    primary_color: '#E81828',
    venue_photo_url:
      'https://commons.wikimedia.org/wiki/Special:FilePath/Citizens%20Bank%20Park%202021.jpg?width=1200',
  },
  {
    external_ref: 'mlb:pittsburgh-pirates',
    league: 'mlb',
    name: 'Pittsburgh Pirates',
    short_name: 'Pirates',
    abbreviation: 'PIT',
    city: 'Pittsburgh',
    state: 'PA',
    conference: 'National League',
    division: 'NL Central',
    venue_name: 'PNC Park',
    venue_address: '115 Federal St, Pittsburgh, PA 15212',
    venue_lat: 40.4469,
    venue_lng: -80.0057,
    timezone: 'America/New_York',
    primary_color: '#FDB827',
    venue_photo_url:
      'https://commons.wikimedia.org/wiki/Special:FilePath/PNC%20Park%2C%20Home%20of%20Pittsburgh%20Pirates.jpg?width=1200',
  },
  {
    external_ref: 'mlb:san-diego-padres',
    league: 'mlb',
    name: 'San Diego Padres',
    short_name: 'Padres',
    abbreviation: 'SD',
    city: 'San Diego',
    state: 'CA',
    conference: 'National League',
    division: 'NL West',
    venue_name: 'Petco Park',
    venue_address: '100 Park Blvd, San Diego, CA 92101',
    venue_lat: 32.7076,
    venue_lng: -117.157,
    timezone: 'America/Los_Angeles',
    primary_color: '#2F241D',
  },
  {
    external_ref: 'mlb:san-francisco-giants',
    league: 'mlb',
    name: 'San Francisco Giants',
    short_name: 'Giants',
    abbreviation: 'SF',
    city: 'San Francisco',
    state: 'CA',
    conference: 'National League',
    division: 'NL West',
    venue_name: 'Oracle Park',
    venue_address: '24 Willie Mays Plaza, San Francisco, CA 94107',
    venue_lat: 37.7786,
    venue_lng: -122.3893,
    timezone: 'America/Los_Angeles',
    primary_color: '#FD5A1E',
    venue_photo_url:
      'https://commons.wikimedia.org/wiki/Special:FilePath/AT%26T%20Park%2C%20San%20Francisco%20at%20night.jpg?width=1200',
  },
  {
    external_ref: 'mlb:seattle-mariners',
    league: 'mlb',
    name: 'Seattle Mariners',
    short_name: 'Mariners',
    abbreviation: 'SEA',
    city: 'Seattle',
    state: 'WA',
    conference: 'American League',
    division: 'AL West',
    venue_name: 'T-Mobile Park',
    venue_address: '1250 1st Ave S, Seattle, WA 98134',
    venue_lat: 47.5914,
    venue_lng: -122.3325,
    timezone: 'America/Los_Angeles',
    primary_color: '#0C2C56',
    venue_photo_url:
      'https://commons.wikimedia.org/wiki/Special:FilePath/SafecoFieldTop.jpg?width=1200',
  },
  {
    external_ref: 'mlb:st-louis-cardinals',
    league: 'mlb',
    name: 'St. Louis Cardinals',
    short_name: 'Cardinals',
    abbreviation: 'STL',
    city: 'St. Louis',
    state: 'MO',
    conference: 'National League',
    division: 'NL Central',
    venue_name: 'Busch Stadium',
    venue_address: '700 Clark Ave, St. Louis, MO 63102',
    venue_lat: 38.6226,
    venue_lng: -90.1928,
    timezone: 'America/Chicago',
    primary_color: '#C41E3A',
    venue_photo_url:
      'https://commons.wikimedia.org/wiki/Special:FilePath/Busch%20Stadium%20from%20top%20of%20the%20Gateway%20Arch.JPG?width=1200',
  },
  {
    // verify: HIGH PRIORITY. Tropicana Field was damaged by Hurricane Milton
    // (Oct 2024) and the Rays played 2025 at George M. Steinbrenner Field in
    // Tampa (27.9805, -82.5069). Confirm which venue the current season uses
    // before enabling — a wrong pin here silently blocks every fan geofence.
    external_ref: 'mlb:tampa-bay-rays',
    league: 'mlb',
    name: 'Tampa Bay Rays',
    short_name: 'Rays',
    abbreviation: 'TB',
    city: 'St. Petersburg',
    state: 'FL',
    conference: 'American League',
    division: 'AL East',
    venue_name: 'Tropicana Field',
    venue_address: '1 Tropicana Dr, St. Petersburg, FL 33705',
    venue_lat: 27.7683,
    venue_lng: -82.6534,
    timezone: 'America/New_York',
    primary_color: '#092C5C',
  },
  {
    external_ref: 'mlb:texas-rangers',
    league: 'mlb',
    name: 'Texas Rangers',
    short_name: 'Rangers',
    abbreviation: 'TEX',
    city: 'Arlington',
    state: 'TX',
    conference: 'American League',
    division: 'AL West',
    venue_name: 'Globe Life Field',
    venue_address: '734 Stadium Dr, Arlington, TX 76011',
    venue_lat: 32.7473,
    venue_lng: -97.0838,
    timezone: 'America/Chicago',
    primary_color: '#003278',
    venue_photo_url:
      'https://commons.wikimedia.org/wiki/Special:FilePath/Globelifefield%20june2020.jpg?width=1200',
  },
  {
    external_ref: 'mlb:toronto-blue-jays',
    league: 'mlb',
    name: 'Toronto Blue Jays',
    short_name: 'Blue Jays',
    abbreviation: 'TOR',
    city: 'Toronto',
    state: 'ON',
    conference: 'American League',
    division: 'AL East',
    venue_name: 'Rogers Centre',
    venue_address: '1 Blue Jays Way, Toronto, ON M5V 1J1',
    venue_lat: 43.6414,
    venue_lng: -79.3894,
    timezone: 'America/Toronto',
    primary_color: '#134A8E',
    venue_photo_url:
      'https://commons.wikimedia.org/wiki/Special:FilePath/Rogers%20Centre%2C%20Toronto%2C%20Ontario%20from%20CN%20Tower%20(21652315548).jpg?width=1200',
  },
  {
    external_ref: 'mlb:washington-nationals',
    league: 'mlb',
    name: 'Washington Nationals',
    short_name: 'Nationals',
    abbreviation: 'WSH',
    city: 'Washington',
    state: 'DC',
    conference: 'National League',
    division: 'NL East',
    venue_name: 'Nationals Park',
    venue_address: '1500 S Capitol St SE, Washington, DC 20003',
    venue_lat: 38.873,
    venue_lng: -77.0074,
    timezone: 'America/New_York',
    primary_color: '#AB0003',
    venue_photo_url:
      'https://commons.wikimedia.org/wiki/Special:FilePath/Aerial%20view%20of%20Nationals%20Park.jpg?width=1200',
  },
];

const WNBA: ProTeamSeed[] = [
  {
    external_ref: 'wnba:atlanta-dream',
    league: 'wnba',
    name: 'Atlanta Dream',
    short_name: 'Dream',
    abbreviation: 'ATL',
    city: 'College Park',
    state: 'GA',
    conference: 'Eastern',
    division: null,
    venue_name: 'Gateway Center Arena',
    venue_address: '2330 Convention Center Concourse, College Park, GA 30337',
    venue_lat: 33.654,
    venue_lng: -84.4487,
    timezone: 'America/New_York',
    primary_color: '#C8102E',
  },
  {
    external_ref: 'wnba:chicago-sky',
    league: 'wnba',
    name: 'Chicago Sky',
    short_name: 'Sky',
    abbreviation: 'CHI',
    city: 'Chicago',
    state: 'IL',
    conference: 'Eastern',
    division: null,
    venue_name: 'Wintrust Arena',
    venue_address: '200 E Cermak Rd, Chicago, IL 60616',
    venue_lat: 41.8534,
    venue_lng: -87.6208,
    timezone: 'America/Chicago',
    primary_color: '#418FDE',
  },
  {
    external_ref: 'wnba:connecticut-sun',
    league: 'wnba',
    name: 'Connecticut Sun',
    short_name: 'Sun',
    abbreviation: 'CON',
    city: 'Uncasville',
    state: 'CT',
    conference: 'Eastern',
    division: null,
    venue_name: 'Mohegan Sun Arena',
    venue_address: '1 Mohegan Sun Blvd, Uncasville, CT 06382',
    venue_lat: 41.4915,
    venue_lng: -72.09,
    timezone: 'America/New_York',
    primary_color: '#FC4C02',
  },
  {
    external_ref: 'wnba:dallas-wings',
    league: 'wnba',
    name: 'Dallas Wings',
    short_name: 'Wings',
    abbreviation: 'DAL',
    city: 'Arlington',
    state: 'TX',
    conference: 'Western',
    division: null,
    venue_name: 'College Park Center',
    venue_address: '600 S Center St, Arlington, TX 76010',
    venue_lat: 32.7307,
    venue_lng: -97.1148,
    timezone: 'America/Chicago',
    primary_color: '#C4D600',
  },
  {
    // verify: expansion franchise, first season 2025.
    external_ref: 'wnba:golden-state-valkyries',
    league: 'wnba',
    name: 'Golden State Valkyries',
    short_name: 'Valkyries',
    abbreviation: 'GSV',
    city: 'San Francisco',
    state: 'CA',
    conference: 'Western',
    division: null,
    venue_name: 'Chase Center',
    venue_address: '1 Warriors Way, San Francisco, CA 94158',
    venue_lat: 37.768,
    venue_lng: -122.3878,
    timezone: 'America/Los_Angeles',
    primary_color: '#5A2D81',
  },
  {
    external_ref: 'wnba:indiana-fever',
    league: 'wnba',
    name: 'Indiana Fever',
    short_name: 'Fever',
    abbreviation: 'IND',
    city: 'Indianapolis',
    state: 'IN',
    conference: 'Eastern',
    division: null,
    venue_name: 'Gainbridge Fieldhouse',
    venue_address: '125 S Pennsylvania St, Indianapolis, IN 46204',
    venue_lat: 39.764,
    venue_lng: -86.1555,
    timezone: 'America/Indiana/Indianapolis',
    primary_color: '#002D62',
  },
  {
    external_ref: 'wnba:las-vegas-aces',
    league: 'wnba',
    name: 'Las Vegas Aces',
    short_name: 'Aces',
    abbreviation: 'LV',
    city: 'Las Vegas',
    state: 'NV',
    conference: 'Western',
    division: null,
    venue_name: 'Michelob Ultra Arena',
    venue_address: '3950 S Las Vegas Blvd, Las Vegas, NV 89119',
    venue_lat: 36.0907,
    venue_lng: -115.1745,
    timezone: 'America/Los_Angeles',
    primary_color: '#000000',
  },
  {
    external_ref: 'wnba:los-angeles-sparks',
    league: 'wnba',
    name: 'Los Angeles Sparks',
    short_name: 'Sparks',
    abbreviation: 'LA',
    city: 'Los Angeles',
    state: 'CA',
    conference: 'Western',
    division: null,
    venue_name: 'Crypto.com Arena',
    venue_address: '1111 S Figueroa St, Los Angeles, CA 90015',
    venue_lat: 34.043,
    venue_lng: -118.2673,
    timezone: 'America/Los_Angeles',
    primary_color: '#552583',
  },
  {
    external_ref: 'wnba:minnesota-lynx',
    league: 'wnba',
    name: 'Minnesota Lynx',
    short_name: 'Lynx',
    abbreviation: 'MIN',
    city: 'Minneapolis',
    state: 'MN',
    conference: 'Western',
    division: null,
    venue_name: 'Target Center',
    venue_address: '600 N 1st Ave, Minneapolis, MN 55403',
    venue_lat: 44.9795,
    venue_lng: -93.2761,
    timezone: 'America/Chicago',
    primary_color: '#236192',
  },
  {
    external_ref: 'wnba:new-york-liberty',
    league: 'wnba',
    name: 'New York Liberty',
    short_name: 'Liberty',
    abbreviation: 'NY',
    city: 'Brooklyn',
    state: 'NY',
    conference: 'Eastern',
    division: null,
    venue_name: 'Barclays Center',
    venue_address: '620 Atlantic Ave, Brooklyn, NY 11217',
    venue_lat: 40.6826,
    venue_lng: -73.9754,
    timezone: 'America/New_York',
    primary_color: '#6ECEB2',
  },
  {
    external_ref: 'wnba:phoenix-mercury',
    league: 'wnba',
    name: 'Phoenix Mercury',
    short_name: 'Mercury',
    abbreviation: 'PHX',
    city: 'Phoenix',
    state: 'AZ',
    conference: 'Western',
    division: null,
    venue_name: 'Mortgage Matchup Center',
    venue_address: '201 E Jefferson St, Phoenix, AZ 85004',
    venue_lat: 33.4457,
    venue_lng: -112.0712,
    timezone: 'America/Phoenix',
    primary_color: '#CB6015',
  },
  {
    external_ref: 'wnba:seattle-storm',
    league: 'wnba',
    name: 'Seattle Storm',
    short_name: 'Storm',
    abbreviation: 'SEA',
    city: 'Seattle',
    state: 'WA',
    conference: 'Western',
    division: null,
    venue_name: 'Climate Pledge Arena',
    venue_address: '334 1st Ave N, Seattle, WA 98109',
    venue_lat: 47.6221,
    venue_lng: -122.3541,
    timezone: 'America/Los_Angeles',
    primary_color: '#2C5234',
  },
  {
    // verify: home arena is the Entertainment & Sports Arena in Congress
    // Heights; the Mystics have also played selected games at Capital One Arena.
    external_ref: 'wnba:washington-mystics',
    league: 'wnba',
    name: 'Washington Mystics',
    short_name: 'Mystics',
    abbreviation: 'WAS',
    city: 'Washington',
    state: 'DC',
    conference: 'Eastern',
    division: null,
    venue_name: 'CareFirst Arena',
    venue_address: '1100 Oak Dr SE, Washington, DC 20032',
    venue_lat: 38.8419,
    venue_lng: -76.9903,
    timezone: 'America/New_York',
    primary_color: '#002B5C',
  },
  {
    // verify: 2026 expansion franchise — confirm venue and that the team is in
    // the provider feed before enabling.
    external_ref: 'wnba:toronto-tempo',
    league: 'wnba',
    name: 'Toronto Tempo',
    short_name: 'Tempo',
    abbreviation: 'TOR',
    city: 'Toronto',
    state: 'ON',
    conference: 'Eastern',
    division: null,
    venue_name: 'Coca-Cola Coliseum',
    venue_address: '100 Princes Blvd, Toronto, ON M6K 3C3',
    venue_lat: 43.634,
    venue_lng: -79.4185,
    timezone: 'America/Toronto',
    primary_color: '#C8102E',
  },
  {
    // verify: 2026 expansion franchise — confirm venue and that the team is in
    // the provider feed before enabling.
    external_ref: 'wnba:portland-fire',
    league: 'wnba',
    name: 'Portland Fire',
    short_name: 'Fire',
    abbreviation: 'POR',
    city: 'Portland',
    state: 'OR',
    conference: 'Western',
    division: null,
    venue_name: 'Moda Center',
    venue_address: '1 N Center Court St, Portland, OR 97227',
    venue_lat: 45.5316,
    venue_lng: -122.6668,
    timezone: 'America/Los_Angeles',
    primary_color: '#E03A3E',
  },
];

/**
 * WWE is a touring promotion, not a league of franchises: there is no home
 * venue and no two-team matchup. It gets one followable row so fans can follow
 * "WWE" and see every show; each show is an Event carrying its own venue and
 * coordinates, with both pro team ids left null.
 */
const WWE: ProTeamSeed[] = [
  {
    external_ref: 'wwe:wwe',
    league: 'wwe',
    name: 'WWE',
    short_name: 'WWE',
    abbreviation: 'WWE',
    city: null,
    state: null,
    conference: null,
    division: null,
    venue_name: null,
    venue_address: null,
    venue_lat: null,
    venue_lng: null,
    timezone: null,
    primary_color: '#0D1B2A',
  },
];

export const PRO_TEAM_SEED: ProTeamSeed[] = [...NFL, ...NBA, ...MLB, ...WNBA, ...WWE];

export const PRO_TEAM_SEED_COUNTS: Record<ProLeague, number> = {
  nfl: NFL.length,
  nba: NBA.length,
  mlb: MLB.length,
  wnba: WNBA.length,
  wwe: WWE.length,
};
