-- Add new notification types for team/game events
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'TEAM_INVITE_ACCEPTED';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'TEAM_INVITE_DECLINED';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'TEAM_MEMBER_REMOVED';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'TEAM_ROLE_CHANGED';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'TEAM_FOLLOWED';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'GAME_CANCELLED';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'GAME_STORY_ADDED';
