import { Router } from 'express';

const publicSiteRouter = Router();

const pageStyle = `body{font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif;max-width:760px;margin:40px auto;padding:0 20px;color:#1F2937;line-height:1.6;background:#F8FAFC}h1{color:#1B3A6B;margin-bottom:8px}h2{color:#2563EB;margin-top:24px}a{color:#2563EB}.card{background:#fff;border:1px solid #E5E7EB;border-radius:18px;padding:28px 24px;box-shadow:0 12px 32px rgba(15,23,42,.08)}.actions{display:flex;flex-wrap:wrap;gap:12px;margin-top:20px}.btn{display:inline-block;background:#1B3A6B;color:#fff;text-decoration:none;padding:12px 18px;border-radius:10px;font-weight:600}.btn-secondary{background:#EFF6FF;color:#1D4ED8}.meta{font-size:14px;color:#64748B;margin-top:20px}`;

publicSiteRouter.get('/', (_req, res) => {
  res.setHeader('Content-Type', 'text/html');
  res.send(`<!DOCTYPE html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width"><title>VarsityHub</title><style>${pageStyle}</style></head><body><div class="card"><h1>VarsityHub</h1><p>VarsityHub is the mobile platform for teams, events, highlights, and fan communities.</p><p>If you opened this page from an email and expected the app to open, go back and tap the full verification or reset link again. Direct deep links like <code>/verify</code> and <code>/reset-password</code> are supported.</p><div class="actions"><a class="btn" href="/support">Support</a><a class="btn btn-secondary" href="/privacy-policy">Privacy Policy</a><a class="btn btn-secondary" href="/terms">Terms of Service</a></div><p class="meta">This domain currently serves VarsityHub's backend and app-link pages. A full consumer web app is separate work.</p></div></body></html>`);
});

publicSiteRouter.get('/privacy-policy', (_req, res) => {
  res.setHeader('Content-Type', 'text/html');
  res.send(`<!DOCTYPE html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width"><title>VarsityHub - Privacy Policy</title><style>${pageStyle}</style></head><body><div class="card"><h1>VarsityHub Privacy Policy</h1><p><em>Last updated: March 25, 2026</em></p><h2>What We Collect</h2><p>Email, username, profile info, posts, photos, videos, messages, team and game data, event RSVPs, device info, usage data, and approximate location when enabled. Payments are processed by Stripe and Apple. We do not store card numbers.</p><h2>How We Use It</h2><p>To run VarsityHub: deliver the service, process payments, send notifications, show nearby events, personalize your experience, and prevent abuse.</p><h2>Who We Share With</h2><p>We do not sell your data. We share only with service providers such as Stripe, Cloudinary, Railway, Google, and Sentry, when you post publicly, or when required by law. We do not share data with sports leagues or universities.</p><h2>Your Rights</h2><p>You can access, correct, delete, or export your data. Delete your account in Settings. Contact <a href="mailto:customerservice@varsityhub.app">customerservice@varsityhub.app</a> for account requests or <a href="mailto:support@varsityhub.app">support@varsityhub.app</a> to report content.</p><h2>Children</h2><p>You must be 13 or older to use VarsityHub. Users 13-17 need parental consent. We delete data from under-13 users immediately.</p><h2>Security</h2><p>Data is encrypted in transit with HTTPS and stored on Railway PostgreSQL in the United States.</p><h2>Contact</h2><p>Customer service: <a href="mailto:customerservice@varsityhub.app">customerservice@varsityhub.app</a><br>Report content: <a href="mailto:support@varsityhub.app">support@varsityhub.app</a></p><p>&copy; 2025 Lime Productions. All rights reserved.</p></div></body></html>`);
});

publicSiteRouter.get('/terms', (_req, res) => {
  res.setHeader('Content-Type', 'text/html');
  res.send(`<!DOCTYPE html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width"><title>VarsityHub - Terms of Service</title><style>${pageStyle}</style></head><body><div class="card"><h1>VarsityHub Terms of Service</h1><p><em>Last updated: March 25, 2026</em></p><h2>1. Agreement</h2><p>By using VarsityHub you agree to these Terms. You must be 13 or older. Users 13-17 require parental consent.</p><h2>2. The Service</h2><p>VarsityHub lets you create and manage sports teams, schedule games, share content, and access premium features via paid subscriptions.</p><h2>3. Your Account</h2><p>Provide accurate information, keep credentials secure, and you are responsible for all activity on your account.</p><h2>4. Rules</h2><p>Do not post illegal or abusive content, impersonate others, upload content you do not own, spam, interfere with the app, bully or threaten users, or upload broadcast or official sports footage.</p><h2>5. Content</h2><p>You own your content. By posting, you grant VarsityHub a license to display it. All fan content must be personally filmed. Official broadcast content is prohibited.</p><h2>6. Subscriptions</h2><p>Rookie: Free. Veteran: $0.99 per month per additional team. Legend: $20 per year unlimited. Auto-renew unless cancelled. Payments are handled by Apple IAP, Google Play, or Stripe.</p><h2>7. DMCA</h2><p>Registered DMCA Designated Service Provider No. DMCA-1070362. Takedown notices: <a href="mailto:support@varsityhub.app">support@varsityhub.app</a>.</p><h2>8. Disclaimers</h2><p>The app is provided as is. VarsityHub is not liable for indirect damages. Total liability is capped at 12 months of payments.</p><h2>9. Disputes</h2><p>Connecticut law governs. Binding arbitration applies, except where small claims law allows otherwise. Class actions are waived.</p><h2>Contact</h2><p>Customer service: <a href="mailto:customerservice@varsityhub.app">customerservice@varsityhub.app</a><br>Report content: <a href="mailto:support@varsityhub.app">support@varsityhub.app</a></p><p>&copy; 2025 Lime Productions. All rights reserved.</p></div></body></html>`);
});

publicSiteRouter.get('/support', (_req, res) => {
  res.setHeader('Content-Type', 'text/html');
  res.send(`<!DOCTYPE html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width"><title>VarsityHub - Support</title><style>${pageStyle}</style></head><body><div class="card"><h1>VarsityHub Support</h1><p>Need help? We are here for you.</p><h2>Contact Us</h2><p><strong>Customer Service</strong> (account, billing, subscriptions):<br><a href="mailto:customerservice@varsityhub.app">customerservice@varsityhub.app</a></p><p><strong>Report Content or Users</strong> (abuse, DMCA, moderation):<br><a href="mailto:support@varsityhub.app">support@varsityhub.app</a></p><h2>Common Topics</h2><ul><li><strong>Account issues:</strong> password reset, email verification, account deletion</li><li><strong>Team management:</strong> creating teams, inviting members, managing rosters</li><li><strong>Subscriptions:</strong> upgrading, downgrading, billing questions</li><li><strong>Content:</strong> reporting abuse, DMCA takedowns, content guidelines</li><li><strong>Technical:</strong> app crashes, bugs, feature requests</li></ul><p>We typically respond within 24 hours.</p><p>&copy; 2025 Lime Productions. All rights reserved.</p></div></body></html>`);
});

export { publicSiteRouter };
