#!/bin/bash
# Email Integration Parameter Fix Script
# This script documents all required parameter fixes

echo "=== Email Parameter Naming Fixes Required ==="
echo ""
echo "1. auth.ts - sendUserConfirmationEmail"
echo "   - user_name → userName"
echo "   - registration_date → confirmationLink"  
echo "   - user_role → (remove, not needed)"
echo "   - next_steps_url → (remove, not needed)"
echo "   - support_email → (remove, not needed)"
echo ""
echo "2. auth.ts - sendLoginNewDeviceEmail → sendLoginFromNewDeviceEmail"
echo "   - user_name → userName"
echo "   - device_type → deviceType"
echo "   - browser → (part of deviceType)"
echo "   - ip_address → deviceLocation"
echo "   - login_date → (part of timestamp)"
echo "   - login_time → (part of timestamp)"
echo "   - secure_account_url → (remove)"
echo "   - support_email → (remove)"
echo ""
echo "3. teams.ts - sendRosterThresholdEmail"
echo "   - coach_name → coachName"
echo "   - team_name → teamName"
echo "   - roster_count → currentRosterCount"
echo "   - threshold → maxRosterCount"
echo "   - threshold_cost → (remove)"
echo "   - manage_billing_url → upgradeLink"
echo ""
echo "4. organizations.ts - sendOrganizationInvitationEmail"
echo "   - invitee_name → recipientName"
echo "   - inviter_name → inviterName"
echo "   - organization_name → organizationName"
echo "   - invite_link → acceptLink"
echo "   - expiry_days → (remove)"
echo "   - (add) declineLink"
echo ""
echo "5. teams.ts - sendTeamInvitationEmail"
echo "   - invitee_name → recipientName"
echo "   - inviter_name → inviterName"
echo "   - team_name → teamName"
echo "   - organization_name → (remove)"
echo "   - invite_link → acceptLink"
echo "   - expiry_days → (remove)"
echo "   - (add) declineLink"
echo ""
echo "6. teams.ts - sendAthleteInvitationEmail"
echo "   - athlete_name → athleteName"
echo "   - coach_name → coachName"
echo "   - team_name → teamName"
echo "   - organization_name → (remove)"
echo "   - position → (remove)"
echo "   - invite_link → acceptLink"
echo "   - expiry_days → (remove)"
echo "   - (add) declineLink"
echo ""
echo "7. teams.ts - sendInvitationDeclinedEmail"
echo "   - sender_name → senderName"
echo "   - declined_by_name → declinedByName"
echo "   - team_name → teamName"
echo "   - declined_date → declinedDate"
echo "   - reason_provided → reasonProvided"
echo "   - view_team_url → viewTeamUrl"
echo "   - resend_invitation_url → resendInvitationUrl"
echo ""
echo "8. teams.ts - sendRoleAssignmentEmail"
echo "   - recipient_name → userName"
echo "   - team_name → teamName"
echo "   - organization_name → (remove)"
echo "   - previous_role → (remove)"
echo "   - new_role → newRole"
echo "   - assigned_by_name → assignedBy"
echo "   - assignment_date → assignedDate"
echo "   - view_team_url → dashboardLink"
echo ""
echo "9. teams.ts - sendTeamRosterUpdateEmail"
echo "   - recipient_name → coachName"
echo "   - team_name → teamName"
echo "   - update_type → updateType"
echo "   - affected_member_name → playerName"
echo "   - affected_member_role → (remove)"
echo "   - action_by_name → (remove)"
echo "   - update_date → updateDate"
echo "   - roster_count → (remove)"
echo "   - view_roster_url → viewRosterLink"
echo ""
echo "10. teams.ts - sendMemberRemovedEmail - MISSING role parameter"
echo ""
echo "11. teams.ts - sendStaffMemberJoinedEmail - NOT IMPORTED"
echo ""
echo "12. events.ts - sendEventRSVPEmail → sendEventRsvpConfirmedEmail"
echo "    - user_name → userName"
echo "    - event_name → eventName"
echo "    - event_date → eventDate (date part only)"
echo "    - (add) eventTime"
echo "    - event_location → eventLocation"
echo "    - rsvp_status → (remove)"
echo "    - attendee_count → (remove)"
echo "    - event_capacity → (remove)"
echo "    - event_details_url → eventDetailLink"
echo "    - cancel_rsvp_url → cancelRsvpLink"
echo "    - (add) rsvpConfirmedAt"
echo "    - (add) organizationName"
echo "    - (add) calendarLink"
echo ""
echo "13. adminReports.ts - sendReportResolvedEmail → sendReportResolutionEmail"
echo ""
echo "14. subscriptionExpiryChecker.ts - sendSubscriptionExpiringEmail"
echo "    - user_name → userName"
echo "    - plan_name → planName"
echo "    - expiry_date → expiresDate"
echo "    - days_remaining → daysRemaining"
echo "    - renewal_url → renewLink"
echo "    - manage_billing_url → manageSubscriptionLink"
echo "    - support_email → (remove)"
echo "    - (add) renewalPrice"
echo "    - (add) featuresLosing"
