export default {
  preset: 'ts-jest/presets/default-esm',
  testEnvironment: 'node',
  extensionsToTreatAsEsm: ['.ts'],
  transform: {
    '^.+\\.(ts|tsx)$': ['ts-jest', { useESM: true, tsconfig: { isolatedModules: true } }],
  },
  roots: ['<rootDir>/src'],
  testMatch: ['**/__tests__/**/*.(spec|test).ts', '**/?(*.)+(spec|test).ts'],
  moduleFileExtensions: ['ts', 'tsx', 'js', 'jsx', 'json', 'node'],
  collectCoverageFrom: [
    'src/**/*.ts',
    '!src/**/*.d.ts',
    '!src/**/index.ts',
    '!src/**/__tests__/**',
  ],
  coverageThreshold: {
    global: {
      branches: 50,
      functions: 50,
      lines: 50,
      statements: 50,
    },
  },
  setupFilesAfterEnv: ['<rootDir>/src/__tests__/setup.cjs'],
  moduleNameMapper: {
    '^@/(.*)$': '<rootDir>/src/$1',
    'debugLog\\.js$': '<rootDir>/src/lib/debugLog.ts',
    '../lib/prisma\\.js$': '<rootDir>/src/lib/prisma.ts',
    '../middleware/requireAdmin\\.js$': '<rootDir>/src/middleware/requireAdmin.ts',
    '../middleware/requireAuth\\.js$': '<rootDir>/src/middleware/requireAuth.ts',
    './load-env\\.js$': '<rootDir>/src/lib/load-env.ts',
    './gameStories\\.js$': '<rootDir>/src/routes/gameStories.ts',
    '\\.\\./lib/geoUtils\\.js$': '<rootDir>/src/lib/geoUtils.ts',
    '\\.\\./lib/geofencing\\.js$': '<rootDir>/src/lib/geofencing.ts',
    '\\./prisma\\.js$': '<rootDir>/src/lib/prisma.ts',
    '\\.\\./lib/errors/AppError\\.js$': '<rootDir>/src/lib/errors/AppError.ts',
    '\\.\\./lib/errors/ValidationError\\.js$': '<rootDir>/src/lib/errors/ValidationError.ts',
    '\\.\\./lib/errors/AuthenticationError\\.js$': '<rootDir>/src/lib/errors/AuthenticationError.ts',
    '\\.\\./lib/errors/AuthorizationError\\.js$': '<rootDir>/src/lib/errors/AuthorizationError.ts',
    '\\.\\./lib/errors/NotFoundError\\.js$': '<rootDir>/src/lib/errors/NotFoundError.ts',
    '\\.\\./lib/errors/ConflictError\\.js$': '<rootDir>/src/lib/errors/ConflictError.ts',
    '\\.\\./lib/errors/RateLimitError\\.js$': '<rootDir>/src/lib/errors/RateLimitError.ts',
    '\\.\\./lib/errors/index\\.js$': '<rootDir>/src/lib/errors/index.ts',
  },
  testTimeout: 10000,
  verbose: true,
};
