#!/bin/bash

###############################################################################
# Database Verification Script: Stripe Role Binding Fix
# 
# This script provides SQL queries to verify the fix in the database
# Run against the production database after manual E2E testing
###############################################################################

echo "📊 Database Verification: Stripe Role Binding Fix"
echo "=================================================="
echo ""

# Check if DATABASE_URL is set
if [ -z "$DATABASE_URL" ]; then
  echo "⚠️  DATABASE_URL not set in environment"
  echo ""
  echo "To use this script:"
  echo "1. Set DATABASE_URL: export DATABASE_URL='postgresql://user:pass@host:5432/varsityhub'"
  echo "2. Run: bash qa-db-verify.sh"
  echo ""
  echo "Or, copy-paste the queries below into your database client:"
  echo ""
fi

echo "Query 1: Check users with Veteran plans"
echo "========================================"
echo ""
echo "SELECT "
echo "  id,"
echo "  email,"
echo "  preferences->>'plan' as plan,"
echo "  preferences->>'role' as role,"
echo "  preferences->>'subscription_id' as subscription_id,"
echo "  created_at"
echo "FROM \"User\""
echo "WHERE preferences->>'plan' = 'veteran'"
echo "ORDER BY created_at DESC"
echo "LIMIT 5;"
echo ""
echo "Expected: All rows should have role='coach', plan='veteran'"
echo ""
echo "---"
echo ""

echo "Query 2: Check users with Legend plans"
echo "======================================="
echo ""
echo "SELECT "
echo "  id,"
echo "  email,"
echo "  preferences->>'plan' as plan,"
echo "  preferences->>'role' as role,"
echo "  preferences->>'subscription_id' as subscription_id,"
echo "  created_at"
echo "FROM \"User\""
echo "WHERE preferences->>'plan' = 'legend'"
echo "ORDER BY created_at DESC"
echo "LIMIT 5;"
echo ""
echo "Expected: All rows should have role='coach', plan='legend'"
echo ""
echo "---"
echo ""

echo "Query 3: Check users with Rookie plans"
echo "========================================"
echo ""
echo "SELECT "
echo "  id,"
echo "  email,"
echo "  preferences->>'plan' as plan,"
echo "  preferences->>'role' as role,"
echo "  created_at"
echo "FROM \"User\""
echo "WHERE preferences->>'plan' = 'rookie'"
echo "ORDER BY created_at DESC"
echo "LIMIT 5;"
echo ""
echo "Expected: All rows should have role='fan', plan='rookie' (or NULL role = fan)"
echo ""
echo "---"
echo ""

echo "Query 4: Verify no users have mismatched plan/role"
echo "==================================================="
echo ""
echo "-- Users with veteran/legend plans but NOT role='coach'"
echo "SELECT "
echo "  id,"
echo "  email,"
echo "  preferences->>'plan' as plan,"
echo "  preferences->>'role' as role"
echo "FROM \"User\""
echo "WHERE (preferences->>'plan' IN ('veteran', 'legend'))"
echo "  AND (preferences->>'role' != 'coach' OR preferences->>'role' IS NULL)"
echo "ORDER BY preferences->>'plan';"
echo ""
echo "Expected: No rows (should be empty)"
echo ""
echo "---"
echo ""

echo "Query 5: Check transaction logs for recent payments"
echo "===================================================="
echo ""
echo "SELECT "
echo "  id,"
echo "  transaction_type,"
echo "  status,"
echo "  user_id,"
echo "  (SELECT email FROM \"User\" WHERE \"User\".id = \"TransactionLog\".user_id) as user_email,"
echo "  stripe_session_id,"
echo "  total_cents,"
echo "  created_at"
echo "FROM \"TransactionLog\""
echo "WHERE transaction_type = 'SUBSCRIPTION_PURCHASE'"
echo "  AND created_at >= NOW() - INTERVAL '24 hours'"
echo "ORDER BY created_at DESC"
echo "LIMIT 10;"
echo ""
echo "Expected: status='COMPLETED' for all recent purchases"
echo ""
echo "---"
echo ""

echo "Query 6: Verify role distribution after fix"
echo "============================================"
echo ""
echo "SELECT "
echo "  COALESCE(preferences->>'role', 'fan') as role,"
echo "  COALESCE(preferences->>'plan', 'rookie') as plan,"
echo "  COUNT(*) as count"
echo "FROM \"User\""
echo "GROUP BY COALESCE(preferences->>'role', 'fan'), COALESCE(preferences->>'plan', 'rookie')"
echo "ORDER BY count DESC;"
echo ""
echo "Expected breakdown:"
echo "  - role='coach', plan='veteran': numerous"
echo "  - role='coach', plan='legend': several"
echo "  - role='fan', plan='rookie': many"
echo "  - role='coach', plan='rookie': none or very few (not affected by fix)"
echo ""
echo "---"
echo ""

echo "Query 7: Check for any data anomalies"
echo "======================================"
echo ""
echo "-- Coaches without subscriptions (should be valid for rookie)"
echo "SELECT "
echo "  id, email,"
echo "  preferences->>'plan' as plan,"
echo "  preferences->>'role' as role,"
echo "  preferences->>'subscription_id' as subscription_id"
echo "FROM \"User\""
echo "WHERE preferences->>'role' = 'coach'"
echo "  AND (preferences->>'subscription_id' IS NULL OR preferences->>'subscription_id' = '')"
echo "ORDER BY created_at DESC;"
echo ""
echo "Expected: Mostly empty (coaches should have subscriptions, unless they cancelled)"
echo ""
echo "---"
echo ""

echo "✅ Copy these queries to your database client and review results"
echo ""
echo "Success Criteria:"
echo "1. Query 1: All veterans have role='coach'"
echo "2. Query 2: All legends have role='coach'"
echo "3. Query 3: All rookies have role='fan'"
echo "4. Query 4: No mismatched plan/role combinations"
echo "5. Query 5: Recent payments show status='COMPLETED'"
echo "6. Query 6: Role/plan distribution looks healthy"
echo "7. Query 7: Coaches mostly have subscription IDs"
echo ""
echo "If all queries pass → FIX VALIDATED ✅"
echo ""
