INSERT INTO "SportsLeague" (
  "id",
  "slug",
  "name",
  "sport_slug",
  "level",
  "gender",
  "country_code",
  "provider",
  "provider_league_id",
  "active"
) VALUES
  ('sports_league_nfl', 'nfl', 'NFL', 'football', 'major', 'men', 'US', 'espn', 'football/nfl', true),
  ('sports_league_nba', 'nba', 'NBA', 'basketball', 'major', 'men', 'US', 'espn', 'basketball/nba', true),
  ('sports_league_wnba', 'wnba', 'WNBA', 'basketball', 'major', 'women', 'US', 'espn', 'basketball/wnba', true),
  ('sports_league_mlb', 'mlb', 'MLB', 'baseball', 'major', 'men', 'US', 'espn', 'baseball/mlb', true),
  ('sports_league_nhl', 'nhl', 'NHL', 'ice_hockey', 'major', 'men', 'US', NULL, NULL, true),
  ('sports_league_mls', 'mls', 'MLS', 'soccer', 'major', 'men', 'US', NULL, NULL, true),
  ('sports_league_nwsl', 'nwsl', 'NWSL', 'soccer', 'major', 'women', 'US', NULL, NULL, true),
  ('sports_league_wwe', 'wwe', 'WWE', 'wrestling', 'major', 'mixed', 'US', 'thesportsdb', '4444', true),
  ('sports_league_ufc', 'ufc', 'UFC', 'mma', 'major', 'mixed', 'US', NULL, NULL, true),
  ('sports_league_pga_tour', 'pga_tour', 'PGA Tour', 'golf', 'major', 'men', 'US', NULL, NULL, true),
  ('sports_league_lpga', 'lpga', 'LPGA', 'golf', 'major', 'women', 'US', NULL, NULL, true),
  ('sports_league_atp', 'atp', 'ATP Tour', 'tennis', 'major', 'men', 'US', NULL, NULL, true),
  ('sports_league_wta', 'wta', 'WTA Tour', 'tennis', 'major', 'women', 'US', NULL, NULL, true),
  ('sports_league_nascar_cup', 'nascar_cup', 'NASCAR Cup Series', 'auto_racing', 'major', 'mixed', 'US', NULL, NULL, true),
  ('sports_league_indycar', 'indycar', 'IndyCar', 'auto_racing', 'major', 'mixed', 'US', NULL, NULL, true),
  ('sports_league_formula_one', 'formula_one', 'Formula 1', 'auto_racing', 'major', 'mixed', NULL, NULL, NULL, true),
  ('sports_league_milb_triple_a', 'milb_triple_a', 'Minor League Baseball Triple-A', 'baseball', 'minor', 'men', 'US', NULL, NULL, true),
  ('sports_league_milb_double_a', 'milb_double_a', 'Minor League Baseball Double-A', 'baseball', 'minor', 'men', 'US', NULL, NULL, true),
  ('sports_league_milb_high_a', 'milb_high_a', 'Minor League Baseball High-A', 'baseball', 'minor', 'men', 'US', NULL, NULL, true),
  ('sports_league_milb_single_a', 'milb_single_a', 'Minor League Baseball Single-A', 'baseball', 'minor', 'men', 'US', NULL, NULL, true),
  ('sports_league_milb_rookie', 'milb_rookie', 'Minor League Baseball Rookie', 'baseball', 'minor', 'men', 'US', NULL, NULL, true),
  ('sports_league_arizona_fall_league', 'arizona_fall_league', 'Arizona Fall League', 'baseball', 'minor', 'men', 'US', NULL, NULL, true),
  ('sports_league_ahl', 'ahl', 'AHL', 'ice_hockey', 'minor', 'men', 'US', NULL, NULL, true),
  ('sports_league_echl', 'echl', 'ECHL', 'ice_hockey', 'minor', 'men', 'US', NULL, NULL, true),
  ('sports_league_sphl', 'sphl', 'SPHL', 'ice_hockey', 'minor', 'men', 'US', NULL, NULL, true),
  ('sports_league_fphl', 'fphl', 'FPHL', 'ice_hockey', 'minor', 'men', 'US', NULL, NULL, true),
  ('sports_league_nba_g_league', 'nba_g_league', 'NBA G League', 'basketball', 'minor', 'men', 'US', NULL, NULL, true),
  ('sports_league_usl_championship', 'usl_championship', 'USL Championship', 'soccer', 'minor', 'men', 'US', NULL, NULL, true),
  ('sports_league_usl_league_one', 'usl_league_one', 'USL League One', 'soccer', 'minor', 'men', 'US', NULL, NULL, true),
  ('sports_league_mls_next_pro', 'mls_next_pro', 'MLS NEXT Pro', 'soccer', 'minor', 'men', 'US', NULL, NULL, true),
  ('sports_league_nisa', 'nisa', 'NISA', 'soccer', 'minor', 'men', 'US', NULL, NULL, true),
  ('sports_league_usl_super_league', 'usl_super_league', 'USL Super League', 'soccer', 'major', 'women', 'US', NULL, NULL, true),
  ('sports_league_ncaaf', 'ncaaf', 'NCAA Football', 'football', 'college', 'men', 'US', 'espn', 'football/college-football', true),
  ('sports_league_ncaaf_fbs', 'ncaaf_fbs', 'NCAA FBS Football', 'football', 'college', 'men', 'US', NULL, NULL, true),
  ('sports_league_ncaaf_fcs', 'ncaaf_fcs', 'NCAA FCS Football', 'football', 'college', 'men', 'US', NULL, NULL, true),
  ('sports_league_ncaamb', 'ncaamb', 'NCAA Men''s Basketball', 'basketball', 'college', 'men', 'US', 'espn', 'basketball/mens-college-basketball', true),
  ('sports_league_ncaawb', 'ncaawb', 'NCAA Women''s Basketball', 'basketball', 'college', 'women', 'US', 'espn', 'basketball/womens-college-basketball', true),
  ('sports_league_ncaabaseball', 'ncaabaseball', 'NCAA Baseball', 'baseball', 'college', 'men', 'US', 'espn', 'baseball/college-baseball', true),
  ('sports_league_ncaasoftball', 'ncaasoftball', 'NCAA Softball', 'softball', 'college', 'women', 'US', NULL, NULL, true),
  ('sports_league_ncaamhockey', 'ncaamhockey', 'NCAA Men''s Ice Hockey', 'ice_hockey', 'college', 'men', 'US', 'espn', 'hockey/mens-college-hockey', true),
  ('sports_league_ncaawhockey', 'ncaawhockey', 'NCAA Women''s Ice Hockey', 'ice_hockey', 'college', 'women', 'US', NULL, NULL, true),
  ('sports_league_ncaamsoccer', 'ncaamsoccer', 'NCAA Men''s Soccer', 'soccer', 'college', 'men', 'US', NULL, NULL, true),
  ('sports_league_ncaawsoccer', 'ncaawsoccer', 'NCAA Women''s Soccer', 'soccer', 'college', 'women', 'US', NULL, NULL, true),
  ('sports_league_ncaamvolleyball', 'ncaamvolleyball', 'NCAA Men''s Volleyball', 'volleyball', 'college', 'men', 'US', NULL, NULL, true),
  ('sports_league_ncaawvolleyball', 'ncaawvolleyball', 'NCAA Women''s Volleyball', 'volleyball', 'college', 'women', 'US', NULL, NULL, true),
  ('sports_league_ncaawbeach_volleyball', 'ncaawbeach_volleyball', 'NCAA Women''s Beach Volleyball', 'beach_volleyball', 'college', 'women', 'US', NULL, NULL, true),
  ('sports_league_ncaamlacrosse', 'ncaamlacrosse', 'NCAA Men''s Lacrosse', 'lacrosse', 'college', 'men', 'US', NULL, NULL, true),
  ('sports_league_ncaawlacrosse', 'ncaawlacrosse', 'NCAA Women''s Lacrosse', 'lacrosse', 'college', 'women', 'US', NULL, NULL, true),
  ('sports_league_ncaamtennis', 'ncaamtennis', 'NCAA Men''s Tennis', 'tennis', 'college', 'men', 'US', NULL, NULL, true),
  ('sports_league_ncaawtennis', 'ncaawtennis', 'NCAA Women''s Tennis', 'tennis', 'college', 'women', 'US', NULL, NULL, true),
  ('sports_league_ncaamgolf', 'ncaamgolf', 'NCAA Men''s Golf', 'golf', 'college', 'men', 'US', NULL, NULL, true),
  ('sports_league_ncaawgolf', 'ncaawgolf', 'NCAA Women''s Golf', 'golf', 'college', 'women', 'US', NULL, NULL, true),
  ('sports_league_ncaamcross_country', 'ncaamcross_country', 'NCAA Men''s Cross Country', 'cross_country', 'college', 'men', 'US', NULL, NULL, true),
  ('sports_league_ncaawcross_country', 'ncaawcross_country', 'NCAA Women''s Cross Country', 'cross_country', 'college', 'women', 'US', NULL, NULL, true),
  ('sports_league_ncaamtrack_field', 'ncaamtrack_field', 'NCAA Men''s Track & Field', 'track_field', 'college', 'men', 'US', NULL, NULL, true),
  ('sports_league_ncaawtrack_field', 'ncaawtrack_field', 'NCAA Women''s Track & Field', 'track_field', 'college', 'women', 'US', NULL, NULL, true),
  ('sports_league_ncaamswimming', 'ncaamswimming', 'NCAA Men''s Swimming & Diving', 'swimming', 'college', 'men', 'US', NULL, NULL, true),
  ('sports_league_ncaawswimming', 'ncaawswimming', 'NCAA Women''s Swimming & Diving', 'swimming', 'college', 'women', 'US', NULL, NULL, true),
  ('sports_league_ncaamgymnastics', 'ncaamgymnastics', 'NCAA Men''s Gymnastics', 'gymnastics', 'college', 'men', 'US', NULL, NULL, true),
  ('sports_league_ncaawgymnastics', 'ncaawgymnastics', 'NCAA Women''s Gymnastics', 'gymnastics', 'college', 'women', 'US', NULL, NULL, true),
  ('sports_league_ncaamwrestling', 'ncaamwrestling', 'NCAA Men''s Wrestling', 'wrestling', 'college', 'men', 'US', NULL, NULL, true),
  ('sports_league_ncaawwrestling', 'ncaawwrestling', 'NCAA Women''s Wrestling', 'wrestling', 'college', 'women', 'US', NULL, NULL, true),
  ('sports_league_ncaafield_hockey', 'ncaafield_hockey', 'NCAA Women''s Field Hockey', 'field_hockey', 'college', 'women', 'US', NULL, NULL, true),
  ('sports_league_ncaawbowling', 'ncaawbowling', 'NCAA Women''s Bowling', 'bowling', 'college', 'women', 'US', NULL, NULL, true),
  ('sports_league_ncaafencing', 'ncaafencing', 'NCAA Fencing', 'fencing', 'college', 'coed', 'US', NULL, NULL, true),
  ('sports_league_ncaarifle', 'ncaarifle', 'NCAA Rifle', 'other', 'college', 'coed', 'US', NULL, NULL, true),
  ('sports_league_ncaaskiing', 'ncaaskiing', 'NCAA Skiing', 'skiing', 'college', 'coed', 'US', NULL, NULL, true),
  ('sports_league_ncaamwater_polo', 'ncaamwater_polo', 'NCAA Men''s Water Polo', 'water_polo', 'college', 'men', 'US', NULL, NULL, true),
  ('sports_league_ncaawwater_polo', 'ncaawwater_polo', 'NCAA Women''s Water Polo', 'water_polo', 'college', 'women', 'US', NULL, NULL, true),
  ('sports_league_ncaawrowing', 'ncaawrowing', 'NCAA Women''s Rowing', 'crew', 'college', 'women', 'US', NULL, NULL, true),
  ('sports_league_ncaawacrobatics_tumbling', 'ncaawacrobatics_tumbling', 'NCAA Women''s Acrobatics & Tumbling', 'acrobatics_tumbling', 'college', 'women', 'US', NULL, NULL, true),
  ('sports_league_ncaawstunt', 'ncaawstunt', 'NCAA Women''s STUNT', 'stunt', 'college', 'women', 'US', NULL, NULL, true)
ON CONFLICT ("slug") DO UPDATE SET
  "name" = EXCLUDED."name",
  "sport_slug" = EXCLUDED."sport_slug",
  "level" = EXCLUDED."level",
  "gender" = EXCLUDED."gender",
  "country_code" = EXCLUDED."country_code",
  "provider" = EXCLUDED."provider",
  "provider_league_id" = EXCLUDED."provider_league_id",
  "active" = EXCLUDED."active";
